spring.application.name=duo
server.port=${SERVER_PORT:8081}

# ===============================
# MySQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/duo?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=q@2468435
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never

management.endpoints.web.exposure.include=health,info